.\" Manpage for list-apt-installs.
.\" Contact zcotcaudle@gmail.com to correct errors or typos.
.TH man 1 "06 May 2018" "0.3" "list-apt-installs man page"
.SH NAME
list-apt-installs \- output apt/apt-get install packages who exist in apt log(s).
.SH SYNOPSIS
list-apt-installs
.SH DESCRIPTION
list-apt-installs is a shell program for listing successful log entries derived from using 'apt install' or 'apt-get install' terminal commands. The output format is designed to work as useful input for working with mint-backup tool restore command.
.SH OPTIONS
The list-apt-installs does not take any options. However you should direct output to a .list file if you intend to use the data with the mint-backup tool to restore previously installed programs.
.SH SEE ALSO
mint-backup(?), 
.SH BUGS
Unintended feature: If you installed a software, then later removed it, this tool will still list the package anyway as it was used with the install command. -so there is not logical interaction from within this tool, it simply lists. It is recommended to check the output file and edit it appropriately.
.SH AUTHOR
Scott Caudle (zcotcaudle@gmail.com)
