.\" Manpage for list-apt-installs.
.\" Contact zcotcaudle@gmail.com to correct errors or typos.
.TH man 1 "06 May 2018" "0.6" "list-apt-installs man page"
.SH NAME
list-apt-installs \- output list of apt/apt-get USER installed packages from apt log(s).
.SH SYNOPSIS
.B list-apt-installs
[\fI\,OPTIONS\/\fR] [\fI\,-o|--output\/\fR[\fI\,=\/\fR] \fI\,</path/and/or/file/name>\/\fR]
.SH DESCRIPTION
list-apt-installs is for listing successful log entries derived from using 'apt install' or 'apt-get install' terminal commands. The default output is formatted for use with the restore function in Linux Mint Backup
tool, or installing with `apt\-get dselect\-upgrade` method. Or output can be formatted as a 'apt install' reinstall script which will need \fBchmod +x\fR to run.
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR=\fI\,FILE\/\fR
Output to FILE instead of standard output
.TP
\fB\-s\fR, \fB\-\-script\fR
Output as `apt install` script.
.TP
\-?, \fB\-\-help\fR
Give this help list
.TP
\fB\-\-usage\fR
Give a short usage message
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version
.PP
Mandatory or optional arguments to long options are also mandatory or optional
for any corresponding short options.
.SH SEE ALSO
\fBapt-get\fR(8),\fBdselect\fR(1)
.SH AUTHOR
Scott Caudle (zcotcaudle@gmail.com)
